### ISSUE TITLE
Possible memory leak in NetworkClient/network.c

### ISSUE THREAD

**Issue by BartMassey** [ayende/generic-network-protocol#1]
In `network_client/network.c` around line 84

        if (!configure_context(state->ctx, options->cert, options->key)) {
                free(state);
                push_ssl_errors();
                push_error(EINVAL, "Unable to configure SSL ctx with provided cert(%s) / key (%s)", options->cert, options->key);
                return NULL;
        }

Need to free `state->ctx` with `SSL_CTX_free()` before freeing `state` in this case, looks like? Not an obviously impactful memory leak; perhaps an attacker could find some way to trigger it?

(I haven't exercised this bug. I just grabbed a random file and started auditing it manually for memory things to see what  I could find; this was the first thing I came across. I was curious how the memory safety was compared to the Rust version you wrote about.)

**Comment by ayende** [comment]
Thanks, you are correct. Fixed here: https://github.com/ayende/generic-network-protocol/commit/d4ec4c6ac0b88215bce0275fca30195b743618a9
